[workspace]
members = [
    "gooey",
    "frontends/renderers/kludgine",
    "frontends/browser",
    "frontends/rasterizer",
    "core",
    "widgets",
    "xtask",
]

# [patch.crates-io]
# easygpu = { path = "../easygpu" }

# [patch."https://github.com/khonsulabs/stylecs.git"]
# stylecs = { path = "../stylecs/stylecs" }

# [patch."https://github.com/khonsulabs/kludgine.git"]
# kludgine = { path = "../kludgine/kludgine" }
