[workspace]
members = [
    "gooey",
    "frontends/renderers/kludgine",
    "frontends/browser",
    "frontends/rasterizer",
    "core",
    "widgets",
    "xtask",
    "integrated-examples/bonsaidb/counter/server",
    "integrated-examples/bonsaidb/counter/client",
    "integrated-examples/bonsaidb/counter/shared",
]

[patch.crates-io]
# easygpu = { path = "../easygpu" }
bonsaidb = { git="https://github.com/khonsulabs/bonsaidb.git", branch="main" }
# bonsaidb = { path="../bonsaidb/bonsaidb" }
actionable = { git="https://github.com/khonsulabs/actionable.git", branch="main" }
# actionable = { path="../actionable/actionable", version="0.1.0-dev.3" }

# [patch."https://github.com/khonsulabs/stylecs.git"]
# stylecs = { path = "../stylecs/stylecs" }

# [patch."https://github.com/khonsulabs/kludgine.git"]
# kludgine = { path = "../kludgine/kludgine" }

# [patch."https://github.com/khonsulabs/khonsu-tools.git"]
# khonsu-tools = { path="../khonsu-tools" }

# [patch."https://github.com/khonsulabs/bonsaidb.git"]
# bonsaidb = { path="../bonsaidb/bonsaidb" }
