[workspace]
members = [
    "gooey",
    "frontends/renderers/kludgine",
    "frontends/browser",
    "frontends/rasterizer",
    "core",
    "widgets",
    "xtask",
    "integrated-examples/pliantdb/counter/server",
    "integrated-examples/pliantdb/counter/client",
    "integrated-examples/pliantdb/counter/shared",
]

# [patch.crates-io]
# easygpu = { path = "../easygpu" }

# [patch."https://github.com/khonsulabs/stylecs.git"]
# stylecs = { path = "../stylecs/stylecs" }

# [patch."https://github.com/khonsulabs/kludgine.git"]
# kludgine = { path = "../kludgine/kludgine" }

# [patch."https://github.com/khonsulabs/khonsu-tools.git"]
# khonsu-tools = { path="../khonsu-tools" }

# [patch."https://github.com/khonsulabs/pliantdb.git"]
# pliantdb = { path="../pliantdb/pliantdb" }
