[package]
name = "gooey"
version = "0.1.0-dev.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "A cross-platform graphical user interface framework"
repository = "https://github.com/khonsulabs/gooey"
license = "MIT OR Apache-2.0"
keywords = ["gui", "ui", "user interface"]
categories = ["gui"]
readme = "../README.md"

[features]
default = ["frontend-kludgine"]
frontend-browser = ["gooey-browser"]
frontend-kludgine = ["gooey-kludgine", "gooey-rasterizer"]

[[example]]
name = "browser"
required-features = ["frontend-browser"]

[[example]]
name = "kludgine"
required-features = ["frontend-kludgine"]

[dependencies]
gooey-kludgine = { path = "../frontends/renderers/kludgine", version = "0.1.0-dev.0", optional = true }
gooey-rasterizer = { path = "../frontends/rasterizer", version = "0.1.0-dev.0", optional = true }
gooey-browser = { path = "../frontends/browser", version = "0.1.0-dev.0", optional = true }
gooey-core = { path = "../core", version = "0.1.0-dev.0" }
gooey-widgets = { path = "../widgets", version = "0.1.0-dev.0" }

[dev-dependencies]
wasm-bindgen = "0.2"
