[package]
name = "gooey"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"

[features]
default = ["frontend-kludgine"]
frontend-browser = ["gooey-browser"]
frontend-kludgine = ["gooey-kludgine", "gooey-rasterizer"]

[dependencies]
gooey-kludgine = { path = "../frontends/renderers/kludgine", optional = true }
gooey-rasterizer = { path = "../frontends/rasterizer", optional = true }
gooey-browser = { path = "../frontends/browser", optional = true }
gooey-core = { path = "../core" }
gooey-widgets = { path = "../widgets" }

[dev-dependencies]
kludgine = { git = "https://github.com/khonsulabs/kludgine.git", branch = "redux" }
