[package]
name = "gooey"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"

[features]
default = ["frontend-kludgine"]
frontend-kludgine = ["gooey-kludgine"]
frontend-browser = ["gooey-browser"]

[dependencies]
gooey-kludgine = { path = "../frontends/kludgine", optional = true }
gooey-browser = { path = "../frontends/browser", optional = true }
gooey-core = { path = "../core" }

[dev-dependencies]
kludgine = { git = "https://github.com/khonsulabs/kludgine.git", branch = "redux" }
