[package]
name = "gooey-rasterizer"
version = "0.1.0-dev.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "A rasterizing frontend for the `gooey` framework."
repository = "https://github.com/khonsulabs/gooey"
license = "MIT OR Apache-2.0"
keywords = ["gui", "ui", "user interface"]
categories = ["gui"]
readme = "../../README.md"

[dependencies]
gooey-core = { path="../../core", version="0.1.0-dev.0" }
gooey-renderer = { path="../../renderer", version="0.1.0-dev.0" }
winit = { version="0.25", default-features=false }

[target.'cfg(target_arch="wasm32")'.dependencies]
winit = { version="0.25", features=["web-sys"] }
